# -*- coding: utf-8 -*-
"""M2_W2_Q2_Eigenvector_Eigenvalues.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12GmQiCkxRWDMjs3hmYchq0PGwCFHiZ1J
"""

import numpy as np

def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)