# -*- coding: utf-8 -*-
"""M2_W1_Ex2_Image_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DElQ7fiqdW4Khx19wwB-eKmHp934rIc1
"""

# Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
import numpy as np
img = mpimg.imread('/content/dog.jpeg')

gray_img_01 = np.mean([img.max(axis=2), img.min(axis=2)], axis=0)
gray_img_01[0 , 0]

gray_img_02 = np.mean(img, axis=2)
print(gray_img_02[0, 0])

gray_img_03 = 0.21 * img[:,:,0] + 0.72 * img[:,:,1] + 0.07 * img[:,:,2]
print(gray_img_03[0, 0])