# -*- coding: utf-8 -*-
"""ÔN LUYỆN CHO MODUL 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j3ovaULkcx38Dh9EFAqFOCToYIBYbYAc

Ngày 2 : Basic Python - For-Loop : Tính lãi suất tiền gửi ngân hàng - Dùng vòng lặp for:
https://drive.google.com/file/d/1Bq2q90Lmxsj1GUUQy7tj1CocK1taPYUt/view
"""

def compute_interest(money, period):
    result = money
    for day in range(period):
        result += result / 365
    return round(result, 3)

# Kiểm tra hàm
print(compute_interest(1, 12))  # Ví dụ 1
print(compute_interest(1, 365))  # Ví dụ 2
print(compute_interest(1, 730))  # Ví dụ 3