# -*- coding: utf-8 -*-
"""ÔN LUYỆN CHO MODUL 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j3ovaULkcx38Dh9EFAqFOCToYIBYbYAc

# Ngày 24: Work with Image Data
https://drive.google.com/file/d/1HR59qJ_BvThGrdw4TmeWnvr4Q8MI-mN2/view
"""

!pip install numpy
!pip install opencv-python

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

# Đọc và hiển thị ảnh:
img = cv2.imread ("/content/1.jpg" ,0)
# Using Matplotlib to display image
plt . imshow ( img , cmap ='gray')
plt . show ()

# Tăng/Giảm độ sáng:
# Read image
img = cv2.imread("/content/1.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Adjust brightness
new_img = img.astype(np.float32) + 50
new_img = np.clip(new_img, 0, 255)
new_img = new_img.astype(np.uint8)

# Display image
plt.imshow(new_img)
plt.show()

# Read image
img = cv2.imread("/content/1.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# Display image
plt.imshow(img)
plt.axis('off')  # Ẩn trục
plt.show()

# Đọc ảnh
img = cv2.imread("/content/1.jpg")

# Chuyển ảnh từ BGR sang xám
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Hiển thị ảnh xám
plt.imshow(gray_img, cmap='gray')
plt.axis('off')  # Ẩn trục
plt.show()

# Đọc ảnh gốc
img = cv2.imread("/content/1.jpg")

# Tăng cường độ sáng lên 50 đơn vị
bright_img = cv2.convertScaleAbs(img, alpha=1, beta=50)

# Giảm cường độ sáng xuống 80 đơn vị
dark_img = cv2.convertScaleAbs(img, alpha=1, beta=-80)

# Hiển thị ảnh
fig, axs = plt.subplots(1, 3, figsize=(15, 5))

axs[0].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
axs[0].set_title('Origin Image')
axs[0].axis('off')

axs[1].imshow(cv2.cvtColor(bright_img, cv2.COLOR_BGR2RGB))
axs[1].set_title('Brightness Image')
axs[1].axis('off')

axs[2].imshow(cv2.cvtColor(dark_img, cv2.COLOR_BGR2RGB))
axs[2].set_title('Darkness Image')
axs[2].axis('off')

plt.show()