# -*- coding: utf-8 -*-
"""M6_W3_MULTIPLE_CHOICE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_0Eofp64KU-yPBIbHRIrIPUOBZ4e0x2N
"""

#Q6
import torch
import torch.nn as nn

# Tạo tensor đầu vào với kích thước (batch_size, seq_len, input_size)
input_tensor = torch.randn(5, 10, 10)  # batch_size=5, seq_len=10, input_size=10

# Khởi tạo LSTM và BiLSTM
lstm = nn.LSTM(input_size=10, hidden_size=20, num_layers=2, batch_first=True)
bilstm = nn.LSTM(input_size=10, hidden_size=20, num_layers=2, batch_first=True, bidirectional=True)

# Dự đoán đầu ra từ LSTM
output_lstm, (hidden_state_lstm, cell_state_lstm) = lstm(input_tensor)

# Dự đoán đầu ra từ BiLSTM
output_bilstm, (hidden_state_bilstm, cell_state_bilstm) = bilstm(input_tensor)

# In kích thước đầu ra
print("Output shape for LSTM:", output_lstm.shape)      # (batch_size, seq_len, hidden_size)
print("Output shape for BiLSTM:", output_bilstm.shape)  # (batch_size, seq_len, 2 * hidden_size)