# -*- coding: utf-8 -*-
"""ÔN LUYỆN CHO MODUL 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j3ovaULkcx38Dh9EFAqFOCToYIBYbYAc

# Ngày 21: Bài toán mã đi tuần
https://drive.google.com/file/d/1Ix-u2eOd8QP8wtqkZSh-c_-76ygnjbPO/view
"""

import numpy as np
import math

# Bước 1: Tạo tập tài liệu mẫu
documents = ["Tôi thích học AI","AI là trí tuệ nhân tạo","AGI là siêu trí tuệ nhân tạo"]

# Bước 2: Tiền xử lý - tách từ và tính tần số
def compute_tf(doc):
    words = doc.split()
    word_count = len(words)
    tf_dict = {}
    for word in words:
        tf_dict[word] = tf_dict.get(word, 0) + 1
    for word, count in tf_dict.items():
        tf_dict[word] = count / word_count
    return tf_dict

# Bước 3: Tính toán IDF
def compute_idf(docs):
    N = len(docs)
    idf_dict = {}
    all_words = set(word for doc in docs for word in doc.split())
    for word in all_words:
        count = sum(word in doc for doc in docs)
        idf_dict[word] = math.log(N / (1 + count))
    return idf_dict

# Bước 4: Tính toán TF - IDF
def compute_tf_idf(tfs, idfs):
    tf_idf_dict = {}
    for word, tf in tfs.items():
        tf_idf_dict[word] = tf * idfs[word]
    return tf_idf_dict

# In kết quả
def results():
    idfs = compute_idf(documents)
    for i, doc in enumerate(documents):
        tfs = compute_tf(doc)
        tf_idf = compute_tf_idf(tfs, idfs)
        print(f"Tài liệu {i + 1} '{doc}': {tf_idf}")

print(results())