# -*- coding: utf-8 -*-
"""M3_P4_XGBoost_Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tO6dMS1swQyMiyIeo3hn4Buk2k3hq5Nb

XGBoost Classifier
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xgboost as xgb
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

dataset_path = '/content/Problem4.csv'
data_df = pd.read_csv(dataset_path)
data_df

X, y = data_df.iloc[:, :-1], data_df.iloc[:, -1]
print("Features (X):")
print(X.head())

print("\nTarget (y):")
print(y.head())

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=7)
print("Training data shape (X_train, y_train): ", X_train.shape, y_train.shape)
print("Testing data shape (X_test, y_test): ", X_test.shape, y_test.shape)

xg_class = xgb.XGBClassifier(seed=7)
xg_class.fit(X_train, y_train)
print("Model training completed.")

preds = xg_class.predict(X_test)
print("Predictions on test data: ", preds[:5])

train_acc = accuracy_score(y_train, xg_class.predict(X_train))
test_acc = accuracy_score(y_test, preds)
print(f'Train ACC: {train_acc}')
print(f'Test ACC: {test_acc}')