# -*- coding: utf-8 -*-
"""ÔN LUYỆN CHO MODUL 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j3ovaULkcx38Dh9EFAqFOCToYIBYbYAc

# Ngày 23: Numpy - Positional Embedding
https://drive.google.com/file/d/1mLuLE1AjwRGgW8F7ykb5XAcpkHFcuaTw/view
"""

import numpy as np

def create_position_matrix(seq_len, embed_size):
    pos_matrix = np.zeros((seq_len, embed_size))
    for k in range(seq_len):
        for j in np.arange(int(embed_size / 2)):
            rad = np.power(10000, 2 * j / embed_size)
            pos_matrix[k, 2 * j] = np.sin(k / rad)
            pos_matrix[k, 2 * j + 1] = np.cos(k / rad)
    return pos_matrix

seq_length = 10
embed_size = 16
position_matrix = create_position_matrix(seq_length, embed_size)
print(position_matrix)