# -*- coding: utf-8 -*-
"""M1_W3_Q3_class_Stack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzB7zKcWtzd5SQBxS1QhR2cBJW96ZGZb
"""

class MyStack:
    def __init__(self, capacity):
        self.capacity = capacity
        self.stack = []

    def is_empty(self):
        return len(self.stack) == 0

    def is_full(self):
        return len(self.stack) == self.capacity

    def push(self, value):
        if not self.is_full():
            self.stack.append(value)
        else:
            raise Exception("Stack is full")

    def pop(self):
        if not self.is_empty():
            return self.stack.pop()
        else:
            raise Exception("Stack is empty")

    def top(self):
        if not self.is_empty():
            return self.stack[-1]
        else:
            raise Exception("Stack is empty")

stack1 = MyStack(capacity=5)

# Push elements onto the stack
stack1.push(1)
stack1.push(2)


print(stack1.is_full())
print( stack1 . top () )
print( stack1 . pop () )
print( stack1 . top () )
print( stack1 . pop () )
print( stack1 . is_empty () )

"""trắc nghiệm"""

print ( stack1 . is_full () )

print ( stack1 . top () )